### ISSUE TITLE
Software Engineering subsection

### ISSUE THREAD

**Issue by rgawdzik** [ayoungprogrammer/CSHandbook#1]
**Note**: This depends on the scope of this website. If it should only be focused on algorithms, this subsection would be irrelevant.

There should be a topic that is focused on common idioms found in the industry, such as Factory, Template, Singleton, etc. patterns, and how they apply in the real world.

**Comment by ayoungprogrammer** [comment]
The scope of the website is more focused on data structures and algorithms. You could probably write a whole other book on software engineering practices and industry programming. You are welcome to write  your own articles and put them in a PR!
